### ISSUE TITLE
Flymake version 0.4?

### ISSUE THREAD

**Issue by Bruce-Connor** [robert-zaremba/flymake-go#2]
Maybe I'm missing something here, but the latest flymake version I can find is 0.3, yet this package requires 0.4. Is that correct?

**Comment by robert-zaremba** [comment]
No, the latest flymake is "0.4.16". You can get it form
* marmolade repository: https://marmalade-repo.org/packages/flymake
* github: https://github.com/illusori/emacs-flymake

**Comment by Bruce-Connor** [comment]
Ok. That explains my issue.
A user who doesn't have marmalade configured will see your package listed (on Melpa) but will get an error when trying to install it (because flymake isn't available). 

It might be worth contacting the flymake author to add the latest version to GNU Elpa. That would ensure flymake-go is always installable. 
Given that the package is in Emacs core, I don't there would be any issues with that.
